# Обмен валют

Простой сайт для обмена валют (RUB ⇄ KZT, RUB ⇄ USD).  
Сайт адаптирован для мобильных устройств.  

## Как работает

1. Пользователь пишет в WhatsApp.
2. Согласовывается курс.
3. Производится обмен.

## Контакты

[Написать в WhatsApp](https://wa.me/77072191913)
